-- MAPPINGS
--
local map = require("core.utils").map

-- Install plugins
-- local customPlugins = require "core.customPlugins"
--
-- customPlugins.add(function(use)
--    use {
--       "max397574/better-escape.nvim",
--       event = "InsertEnter",
--    }
--
--    use {
--       "wakatime/vim-wakatime",
--    }
--
--   use {
--       'neovim/nvim-lspconfig',
--       "williamboman/nvim-lsp-installer",
--       config = function()
--          local lsp_installer = require "nvim-lsp-installer"
--
--          lsp_installer.on_server_ready(function(server)
--             local opts = {}
--
--             server:setup(opts)
--             vim.cmd [[ do User LspAttachBuffers ]]
--          end)
--       end,
--    }
--
--   use {
--    "Pocco81/AutoSave.nvim",
--    config = function()
--       local autosave = require "autosave"
--
--       autosave.setup {
--          enabled = true,
--          execution_message = "autosaved at : " .. vim.fn.strftime "%H:%M:%S",
--          events = { "InsertLeave", "TextChanged" },
--          conditions = {
--             exists = true,
--             filetype_is_not = {},
--             modifiable = true,
--          },
--          clean_command_line_interval = 2500,
--          on_off_commands = true,
--          write_all_buffers = false,
--       }
--    end,
--   }
--
--    use {
--      "sbdchd/neoformat"
--    }
-- end)
--
-- -- NOTE: we heavily suggest using Packer's lazy loading (with the 'event','cmd' fields)
-- -- see: https://github.com/wbthomason/packer.nvim
-- -- https://nvchad.github.io/config/walkthrough
